### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-scanjs-rules"

### ISSUE THREAD

**Issue by nirvana-msu** [mozfreddyb/eslint-config-scanjs#6]
If I follow installation instructions and try to use the rules with IntelliJ IDEA, ESLint fails with the following error:

> ESLint couldn't find the plugin "eslint-plugin-scanjs-rules". This can happen for a couple different reasons:
> 
> 1. If ESLint is installed globally, then make sure eslint-plugin-no-unsafe-innerhtml is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin. 
> ...

This seems to be because `scanjs-rules` and `no-unsafe-innerhtml` plugins are not installed globally, but rather just as a dependency of `eslint-config-scanjs` module, so ESLint cannot find them. Installing these two modules globally solves the problem for me:

```sh
npm install eslint-plugin-scanjs-rules -g
npm install eslint-plugin-no-unsafe-innerhtml -g
```

Am I doing something wrong?

**Comment by mozfreddyb** [comment]
> Am I doing something wrong?

I must have broken it in https://github.com/mozfreddyb/eslint-config-scanjs/commit/519a78a885bd6508f3b38076231e87026f1517b6. Sorry.
This happened because I'm currently not using *eslint-config-scanjs* myself.

It seems the README needs an update and. Would you be interested in creating a pull request, @nirvana-msu?

**Comment by cancerberoSgx** [comment]
I think this issue is important for people testing this project for the first time. This work without having to install anything globally

```
cd my_project
npm install --save-dev eslint  https://github.com/mozfreddyb/eslint-plugin-scanjs-rules https://github.com/mozfreddyb/eslint-config-scanjs-rules
node node_modules/eslint/bin/eslint.js  --no-eslintrc -c node_modules/eslint-config-scanjs/.eslintrc .
```
I'm not an eslint expert and I dont like to install several eslint modules globally and also I don't like the previous commands (too complex) so I'm not sure which is the best option and so I wont pull request :(

**Comment by acao** [comment]
The issue is that the published version of the published package doesn't include the necessary files.

The package is there, but the eslint config is not
